{
 "title": "EcomOps Platform Dashboard",
 "tags": [
  "ecomops",
  "flask"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Rate (req/sec)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_total[5m])",
     "legendFormat": "{{ service }} - {{ method }} {{ status }}"
    }
   ]
  },
  {
   "title": "Response Time (p95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(flask_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "{{ service }} - {{ method }}"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(flask_http_request_total{status=~\"5..\"}[5m])) / sum(rate(flask_http_request_total[5m]))) * 100",
     "legendFormat": "Error %"
    }
   ]
  },
  {
   "title": "Container Health (Up/Down)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "up{job=~\"product-service|cart-service|frontend\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"ecomops\"}",
     "legendFormat": "{{ pod }} - {{ container }}"
    }
   ]
  }
 ]
}