apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: ecomops
  labels:
    app: cart-service
    app.kubernetes.io/name: cart-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: ecomops-platform
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
    - port: 5000
      targetPort: 5000
      name: http
      protocol: TCP
  sessionAffinity: None
