apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ecomops
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: ecomops-platform
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: frontend
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: ecomops-platform
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
        - name: frontend
          image: preet8808/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          env:
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: ecomops-config
                  key: FLASK_ENV
            - name: FLASK_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: ecomops-config
                  key: FLASK_DEBUG
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecomops-config
                  key: PRODUCT_SERVICE_URL
            - name: CART_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecomops-config
                  key: CART_SERVICE_URL
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: ecomops-config
                  key: APP_PORT
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      restartPolicy: Always
