apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ecomops
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: ecomops-platform
spec:
  # Use NodePort for demo; in production, use LoadBalancer or Ingress
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
      name: http
      protocol: TCP
  sessionAffinity: None
