name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Test File
        run: |
          echo "GitHub Actions is working!" > report.txt
          echo "Build Time: $(date)" >> report.txt
          cat report.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-report
          path: report.txt